In [ ]:
# Ankushdeep Singh_102003174
# ass6_2

In [106]:
import random
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.naive_bayes import GaussianNB

from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report, confusion_matrix

In [107]:
rows=25

In [108]:
max_percent=100
r=np.random.rand(1)
while r<0.4:
    r=np.random.rand(1)

grad_percent=np.array(max_percent*r)
for i in range(rows-1):
    r=np.random.rand(1)
    while r<0.4:
        r= np.random.rand(1)
    grad_percent=np.append(grad_percent,max_percent*r)
    
grad_percent

array([87.4719654 , 54.4832545 , 50.89261741, 78.13106602, 76.86634042,
       53.47071663, 89.36949073, 99.09214699, 55.65517438, 40.94944071,
       91.45305186, 73.17771683, 79.61062386, 78.79051707, 78.17830949,
       42.1154976 , 43.23853288, 78.16131908, 54.92873463, 82.33215804,
       45.70910472, 78.03835255, 70.960917  , 74.6598852 , 53.89194246])

In [109]:
experience=np.array(random.randint(1,10))
for i in range(rows-1):
    experience=np.append(experience,random.randint(1,10))   
experience

array([ 6,  4,  8,  5,  5,  3,  3,  8,  6,  4,  7,  4,  7,  3,  7,  3,  7,
        6,  4,  2,  4,  9,  3, 10,  5])

In [110]:
written_score=np.array(random.randint(1,10))
for i in range(rows-1):
    written_score=np.append(written_score,random.randint(1,10))   
written_score

array([ 5,  9,  9,  3,  2,  5,  5,  2, 10,  6,  3,  2,  6,  4,  8,  1,  3,
        3,  5, 10,  2, 10,  8,  6,  4])

In [111]:
interview_score=np.array(random.randint(1,10))
for i in range(rows-1):
    interview_score=np.append(interview_score,random.randint(1,10))   
interview_score

array([ 1,  6, 10,  2,  2,  5,  2,  1,  1,  8,  8, 10,  7,  3,  8,  9,  9,
        4, 10,  9,  3,  5,  5,  2,  2])

In [112]:
selection=np.array(random.randint(0,1),dtype=int)
for i in range(rows-1):
    selection=np.append(selection,random.randint(0,1))   
selection

array([1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0,
       0, 1, 1])

In [113]:
data = np.array((grad_percent,experience,written_score,interview_score,selection)) 
data

array([[87.4719654 , 54.4832545 , 50.89261741, 78.13106602, 76.86634042,
        53.47071663, 89.36949073, 99.09214699, 55.65517438, 40.94944071,
        91.45305186, 73.17771683, 79.61062386, 78.79051707, 78.17830949,
        42.1154976 , 43.23853288, 78.16131908, 54.92873463, 82.33215804,
        45.70910472, 78.03835255, 70.960917  , 74.6598852 , 53.89194246],
       [ 6.        ,  4.        ,  8.        ,  5.        ,  5.        ,
         3.        ,  3.        ,  8.        ,  6.        ,  4.        ,
         7.        ,  4.        ,  7.        ,  3.        ,  7.        ,
         3.        ,  7.        ,  6.        ,  4.        ,  2.        ,
         4.        ,  9.        ,  3.        , 10.        ,  5.        ],
       [ 5.        ,  9.        ,  9.        ,  3.        ,  2.        ,
         5.        ,  5.        ,  2.        , 10.        ,  6.        ,
         3.        ,  2.        ,  6.        ,  4.        ,  8.        ,
         1.        ,  3.        ,  3.        ,  5

In [114]:
df = pd.DataFrame(data.transpose(),columns=['grad_percent','experience','written_score','interview_score','selection'])
df=df.astype({'selection':int})
df

grad_percent  experience  written_score  interview_score  selection
0      87.471965         6.0            5.0              1.0          1
1      54.483254         4.0            9.0              6.0          1
2      50.892617         8.0            9.0             10.0          0
3      78.131066         5.0            3.0              2.0          1
4      76.866340         5.0            2.0              2.0          1
5      53.470717         3.0            5.0              5.0          0
6      89.369491         3.0            5.0              2.0          1
7      99.092147         8.0            2.0              1.0          0
8      55.655174         6.0           10.0              1.0          1
9      40.949441         4.0            6.0              8.0          1
10     91.453052         7.0            3.0              8.0          1
11     73.177717         4.0            2.0             10.0          1
12     79.610624         7.0            6.0              7.0          1
13     78.790517         3.0            4.0              3.0          0
14     78.178309         7.0            8.0              8.0          1
15     42.115498         3.0            1.0              9.0          0
16     43.238533         7.0            3.0              9.0          1
17     78.161319         6.0            3.0              4.0          1
18     54.928735         4.0            5.0             10.0          1
19     82.332158         2.0           10.0              9.0          0
20     45.709105         4.0            2.0              3.0          0
21     78.038353         9.0           10.0              5.0          0
22     70.960917         3.0            8.0              5.0          0
23     74.659885        10.0            6.0              2.0          1
24     53.891942         5.0            4.0              2.0          1

In [115]:
x = df.loc[:,df.columns!='selection']         
y = df['selection']

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2,random_state=3)

In [116]:
gnb = GaussianNB()
gnb.fit(x_train, y_train)
y_pred = gnb.predict(x_test)

print(accuracy_score(y_test, y_pred))
print(classification_report(y_test, y_pred))

0.6
              precision    recall  f1-score   support

           0       0.00      0.00      0.00         1
           1       0.75      0.75      0.75         4

    accuracy                           0.60         5
   macro avg       0.38      0.38      0.38         5
weighted avg       0.60      0.60      0.60         5



In [117]:
report = classification_report(y_test, y_pred, output_dict=True)
df_report = pd.DataFrame(report).transpose()
df_report

precision  recall  f1-score  support
0                 0.000   0.000     0.000      1.0
1                 0.750   0.750     0.750      4.0
accuracy          0.600   0.600     0.600      0.6
macro avg         0.375   0.375     0.375      5.0
weighted avg      0.600   0.600     0.600      5.0

In [118]:
df_report.to_csv('created_dataset.csv')

In [119]:
'''(a)90 %, 5 Yrs experience, 8 written test score, 10 interview score
(b) 75%, 8 Yrs experience, 7 written test score, 6 interview score'''

x_predict=np.array([[90,5,18,10],[75,8,7,6]])
x_predict=x_predict.reshape(2,-1)
x_predict.shape

(2, 4)

In [120]:
pr=gnb.predict(x_predict)
print('Results with Gaussian NB: ')
for i in range(x_predict.shape[0]):
    print('Experience:',x_predict[i][0],', Written score:',x_predict[i][1], ', Interview score:',x_predict[i][2])
    print('Selection: ',pr[i])

Results with Gaussian NB: 
Experience: 90 , Written score: 5 , Interview score: 18
Selection:  0
Experience: 75 , Written score: 8 , Interview score: 7
Selection:  0


d:\SOFTWARE INSTALLED\PYTHON\Lib\site-packages\sklearn\base.py:464: UserWarning: X does not have valid feature names, but GaussianNB was fitted with feature names
  warnings.warn(
